### ISSUE TITLE
Linq expression querying ProductInstallation collection must be filtered.

### ISSUE THREAD

**Issue by konste** [tsasioglu/Total-Uninstaller#1]
In InstalledItemsViewModel.cs, LoadUninstallableItems(), GetProducts may occasionally return empty records. In your select statement you query "ins.InstallDate" and for empty record it blows up with ArgumentNullException which eventually surfaces as unhandled (and very obscure) ParseXamlException.

Solution is very simple: insert " .Where(ins => ins.ProductName != null) "
after GetProducts and before Select part of the Linq expression.

Konstantin

**Comment by tsasioglu** [comment]
Done, thanks.
