### ISSUE TITLE
How to select item by keyboard?

### ISSUE THREAD

**Issue by yevhen** [tsasioglu/Total-Uninstaller#10]
I'm trying to select (put mark) item by using Space, Enter, Ctrl-Enter and other frequently used keys, but nothing happens. The selection is only possible by clicking a mouse, which is tedious and not very efficient.

**Comment by tsasioglu** [comment]
You can select rows (using ctrl/shift + click), then right click -> mark for uninstall.
But I'll look at adding some keyboard shortcuts too.

**Comment by tsasioglu** [comment]
Space key now (un)toggles the un(install) checkbox for all selected rows. 

Enjoy
