### ISSUE TITLE
Application must request Admin permissions explicitly

### ISSUE THREAD

**Issue by konste** [tsasioglu/Total-Uninstaller#3]
In case it is accidentaly run as non-administrator - it crashes without showing any message, leaving users in deep confusion.

You'll want to add the manifest and embed it in the program. Project + Add New Item, select "Application Manifest File". Change the <requestedExecutionLevel> element to:
 <requestedExecutionLevel level="requireAdministrator" uiAccess="false" />
The user gets the UAC prompt when they start the program. 

Kostya

**Comment by tsasioglu** [comment]
Done, thanks. 
Although it's still unsigned so shows an extra warning unfortunately.
