### ISSUE TITLE
Nothing happens after clicking "Uninstall"

### ISSUE THREAD

**Issue by jitbit** [tsasioglu/Total-Uninstaller#6]
I tick a component (any component, tried with Windows Phone SDK and other VS bloatware), click "Uninstall" - "OK" confirm - nothing happens.

Windows 8, VS 2013 community edition

**Comment by tsasioglu** [comment]
Hi, is there anything in the logs?
%appdata%/TotalUninstaller

**Comment by jitbit** [comment]
no such folder

**Comment by tsasioglu** [comment]
Small bug :) 
If you download and run now it should be logging.

**Comment by jitbit** [comment]
The updated version seems to work fine (uninstall launches), thanks!

**Comment by matteocontrini** [comment]
Close?
