### ISSUE TITLE
Selecting multiple items

### ISSUE THREAD

**Issue by Trass3r** [tsasioglu/Total-Uninstaller#7]
I can't figure out a way to check multiple items at once.
Selecting a bunch and clicking a checkbox or hitting space or a potential context menu doesn't work.
Neither does the usual next best solution with alternating space and down keys.

**Comment by Trass3r** [comment]
Ah I see you have to do Down->Tab->Space :/

**Comment by tsasioglu** [comment]
It's probably safer to uninstall in small batches, in case something goes wrong...

**Comment by tsasioglu** [comment]
But I've implemented it anyway.
Select a bunch of items -> right click -> "Mark for uninstall"

![image](https://cloud.githubusercontent.com/assets/10605425/7259206/a5121330-e859-11e4-9360-af870734596d.png)

**Comment by Trass3r** [comment]
Thanks!
